# Generated by Django 3.2.12 on 2022-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='A number assigned by the OS to refer to a user\n                     (taken from /etc/passwd)', verbose_name='UID#')),
                ('user', models.CharField(help_text='Username (can be UID in some OS) owning the process', max_length=80, verbose_name='Username or UID')),
                ('pid', models.IntegerField(help_text='Process ID of the process', verbose_name='Procces ID')),
                ('cpu', models.DecimalField(decimal_places=2, help_text='CPU time used by this process (in percentage)', max_digits=5, verbose_name='CPU usage')),
                ('mem', models.DecimalField(decimal_places=2, help_text='Physical memory used by this process (in percentage)', max_digits=5, verbose_name='Memory usage')),
                ('vsz', models.IntegerField(help_text='Virtual memory size used by this process (in KiB)', verbose_name='Virtual memory size')),
                ('rss', models.IntegerField(help_text='Resident Set Size, the non-swappable physical\n                     memory used by this process (in KiB)', verbose_name='Resident memory size')),
                ('tty', models.CharField(help_text='Terminal from which this process is started. Question mark (?) sign\n                     represents that this process is not started from a terminal', max_length=255, verbose_name='Controlling tty')),
                ('stat', models.CharField(help_text='The process state code', max_length=255, verbose_name='Process state')),
                ('start', models.TimeField(help_text='Starting time or date of the process', verbose_name='Starting time or date')),
                ('time', models.TimeField(help_text='Cumulative CPU time', verbose_name='Cumulative CPU time')),
                ('command', models.TextField(help_text='The command with all its arguments which started this process', verbose_name='Command')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
    ]
